### PR TITLE
Update input.js

### LINKED ISSUE #8: compression percentage calculation is wrong

### PR DESCRIPTION
**Pull request by kgashok**
Fixed #8 - compression percentage calculated has been fixed.

### CODE REVIEW

**Comment by WesCossick** [comment]
Can you provide more information about the problem and how this solves it?

**Comment by kgashok** [comment]
The original calculation was 
```javascript
result.compression_percentage = (1 - (result.file_output.length / text.length)) * 100;
```
The **numerator** `result.file_output.length` is in number of *bits*, while the **denominator** `text.length` is in number of *bytes*. Therefore the percentage calculation was wrong. When I changed the denominator to `text.length * 8`, the calculation was fixed.

**Comment by WesCossick** [comment]
I'd have to verify to be certain, but I'm relatively confident that the `file_output` variable is an array of bytes (or more specifically, numbers that represent 8-bit unsigned integers). It's a [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array):

> The Uint8Array typed array represents an array of 8-bit unsigned integers

**Comment by kgashok** [comment]
@WesCossick - In that case, what explains these negative percentages? (for input of "abc"). By the way, I am using the latest version of Chrome on a Chromebook.

Screenshot 2020-01-30 at 08 41 11
Screenshot 2020-01-30 at 08 41 06

**Comment by kgashok** [comment]
And on my forked version (https://shining-baroness.glitch.me/), with the new calculation, I get this:

Screenshot 2020-01-30 at 08 45 48

**Comment by WesCossick** [comment]
That's expected, and exactly what this app is designed to help users visualize. Huffman encoding is designed for longer strings that use a limited set of characters. Shorter strings like `abc` which have no repeated characters will actually take up more space when compressed with Huffman encoding than if they weren't compressed at all.

I would recommend learning more about Huffman encoding: https://en.wikipedia.org/wiki/Huffman_coding

**Pull request closed without merging**
